name: mac-os-ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build-macos:
    runs-on: macos-14
    timeout-minutes: 40  # ✨✨✨✨
    steps:
      - uses: actions/checkout@v4
      - run: |
          brew update && brew install ninja boost automake libtool
      - name: Configure CMake
        run: |
          cmake --version
          gcc-12 --version
          uname -a
          cmake -B ${{github.workspace}}/build \
            -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
            -GNinja \
            -DCMAKE_C_COMPILER=gcc-12 \
            -DCMAKE_CXX_COMPILER=g++-12 \
            -DCMAKE_CXX_FLAGS="-Wl,-ld_classic"  # due to a linker bug on macos, see https://github.com/Homebrew/homebrew-core/issues/145991

      - name: Build & Test
        run: |
          cd ${{github.workspace}}/build
          cat CMakeCache.txt
          
          ninja gperf_project || cat third_party/src/gperf_project-stamp/gperf_project-install-*.log
          ninja cares_project || cat third_party/src/cares_project-stamp/cares_project-build-*.log
          ninja -k 5 base/all io/all strings/all util/all echo_server ping_iouring_server \
            https_client_cli s3_demo
          ./fibers_test --logtostderr --gtest_repeat=10
          GLOG_logtostderr=1 ctest -V -L CI
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: third_party_logs
          path: |
            ${{github.workspace}}/build/third_party/src/**/*.log